### ISSUE TITLE
eom cannot handle hugh images

### ISSUE THREAD

**Issue by maandree** [mate-desktop/eom#140]
I made an 1038 × 46242 pixel image, but eom can't display it.

**Comment by flexiondotorg** [comment]
What can display that image?

**Comment by maandree** [comment]
The thumbnailer caja uses.
feh glitches, but it's better then eom.
Firefox, GIMP and Dooble can display it without any problem, although Firefox takes half a second to load it.
I haven't tested any other programs.

**Comment by raveit65** [comment]
Hard to reproduce without a download link to the image.

**Comment by rcaridade145** [comment]
@raveit65  https://bugzilla.gnome.org/show_bug.cgi?id=672990#c2 can this be the case?

**Comment by raveit65** [comment]
Hard to say, i can't open the test file, but fedora 28 use librsvg2-2.42.6-1.fc28.x86_64
So no chance to downgrade to 2.34 for testing.
And eog report is closed.

**Comment by hewhodares** [comment]
> What can display that image?

@flexiondotorg 

Decent software can. Stuff I've written and worked with in the past lets you set a mask (usually just a rectangle, some software a square rectangle, some rarer still, square with powers of 2 for each side - but those were textures so ...)

Where you say "I want this bit" and it discards everything else, rendering just where you said. 

The cost is you have to *render* (rather than render entire image to a bitmap to display, or compressed image for GPU to blit in - doubtful this is used) as you pan around the image. So you may scroll and see the image loading in after you've scrolled.

Zooming out can be a problem for these, as sampling done in a memory aware way is rather difficult BUT IT CAN BE DONE. You just have to render small bits, sample them however you do, then discard that one bit. 

It can be done fairly quickly in practice (that is the mask overhead is tiny)

I'm getting so annoyed with EOM I'm going to start digging and if needed (help/sponsor/do) fixing, If there's no open source jpeg library "worth it" by having the above (and for a few other types) I've offered to make one, but I really hope it doesn't come to that.

**Comment by samtygier** [comment]
There are some suitably large images on wikimedia, e.g. https://upload.wikimedia.org/wikipedia/commons/e/e1/Hieronymus_Bosch_-_The_Garden_of_Earthly_Delights_-_Prado_in_Google_Earth-x0-y0.jpg

This will open in GIMP and display (ImageMagik), but crash EOM. I get the following backtrace

```
Thread 1 "eom" received signal SIGSEGV, Segmentation fault.
0x00007ffff5cc6d01 in bits_image_fetch_separable_convolution_affine (repeat_mode=PIXMAN_REPEAT_PAD, format=PIXMAN_x8r8g8b8, convert_pixel=<optimized out>, 
    mask=<optimized out>, buffer=0x7fffffff44c0, width=<optimized out>, line=<optimized out>, offset=<optimized out>, image=0x555555793b40) at pixman-fast-path.c:3083
3083	    return *(((uint32_t *)row) + x);
(gdb) bt
#0  0x00007ffff5cc6d01 in bits_image_fetch_separable_convolution_affine (repeat_mode=PIXMAN_REPEAT_PAD, format=PIXMAN_x8r8g8b8, convert_pixel=<optimized out>, 
    mask=<optimized out>, buffer=0x7fffffff44c0, width=<optimized out>, line=<optimized out>, offset=<optimized out>, image=0x555555793b40) at pixman-fast-path.c:3083
#1  bits_image_fetch_separable_convolution_affine_pad_x8r8g8b8 (iter=0x7fffffff43a0, mask=0x0) at pixman-fast-path.c:3154
#2  0x00007ffff5cda304 in general_composite_rect (imp=0x5555555f2370, info=<optimized out>) at pixman-general.c:220
#3  0x00007ffff5c958b1 in pixman_image_composite32 (op=op@entry=PIXMAN_OP_SRC, src=src@entry=0x555555793b40, mask=mask@entry=0x0, dest=dest@entry=0x555555cabaf0, 
    src_x=0, src_y=0, mask_x=0, mask_y=0, dest_x=0, dest_y=0, width=600, height=585) at pixman.c:700
#4  0x00007ffff6ae13c1 in composite_boxes (_dst=<optimized out>, op=<optimized out>, abstract_src=<optimized out>, abstract_mask=<optimized out>, src_x=0, src_y=0, 
    mask_x=0, mask_y=0, dst_x=0, dst_y=0, boxes=0x7fffffffabe0, extents=0x7fffffffaeac) at cairo-image-compositor.c:538
#5  0x00007ffff6b1a9a5 in composite_aligned_boxes (boxes=0x7fffffffabe0, extents=0x7fffffffae70, compositor=0x7ffff6bce8c0 <spans>) at cairo-spans-compositor.c:683
#6  clip_and_composite_boxes (compositor=compositor@entry=0x7ffff6bce8c0 <spans>, extents=extents@entry=0x7fffffffae70, boxes=boxes@entry=0x7fffffffabe0)
    at cairo-spans-compositor.c:882
#7  0x00007ffff6b1b0ee in clip_and_composite_boxes (compositor=0x7ffff6bce8c0 <spans>, extents=0x7fffffffae70, boxes=0x7fffffffabe0) at cairo-spans-compositor.c:841
#8  0x00007ffff6b1b170 in _cairo_spans_compositor_paint (_compositor=0x7ffff6bce8c0 <spans>, extents=0x7fffffffae70) at cairo-spans-compositor.c:983
#9  0x00007ffff6ad5301 in _cairo_compositor_paint (compositor=0x7ffff6bce8c0 <spans>, surface=0x555555659c00, op=<optimized out>, source=<optimized out>, 
    clip=<optimized out>) at cairo-compositor.c:65
#10 0x00007ffff6b26f34 in _cairo_surface_paint (clip=0x0, source=0x7fffffffb1e0, op=CAIRO_OPERATOR_SOURCE, surface=0x555555659c00) at cairo-surface.c:2198
#11 _cairo_surface_paint (surface=surface@entry=0x555555659c00, op=op@entry=CAIRO_OPERATOR_SOURCE, source=source@entry=0x7fffffffb1e0, clip=clip@entry=0x0)
    at cairo-surface.c:2171
#12 0x00007ffff6b21aa3 in _cairo_surface_offset_paint (target=target@entry=0x555555659c00, x=<optimized out>, y=0, op=op@entry=CAIRO_OPERATOR_SOURCE, 
    source=0x7fffffffb1e0, source@entry=0x7fffffffbce0, clip=clip@entry=0x0) at cairo-surface-offset.c:85
#13 0x00007ffff6b4d772 in render_pattern (dst=dst@entry=0x555555cb5cb0, pattern=pattern@entry=0x7fffffffbce0, is_mask=<optimized out>, extents=0x7fffffffbc9c, 
    src_x=0x7fffffffb53c, src_y=0x7fffffffb540) at cairo-xlib-source.c:306
#14 0x00007ffff6b4eb6a in _cairo_xlib_source_create_for_pattern (_dst=0x555555cb5cb0, pattern=0x7fffffffbce0, is_mask=<optimized out>, extents=0x7fffffffbc9c, 
    sample=<optimized out>, src_x=0x7fffffffb53c, src_y=0x7fffffffb540) at cairo-xlib-source.c:1168
#15 0x00007ffff6b2ebe9 in composite_aligned_boxes (boxes=0x7fffffffb9d0, extents=0x7fffffffbc60, compositor=0x7ffff6bcfcc0 <compositor>)
    at cairo-traps-compositor.c:1292
#16 clip_and_composite_boxes (compositor=compositor@entry=0x7ffff6bcfcc0 <compositor>, extents=extents@entry=0x7fffffffbc60, boxes=boxes@entry=0x7fffffffb9d0)
    at cairo-traps-compositor.c:1792
#17 0x00007ffff6b2ed5c in clip_and_composite_boxes (compositor=0x7ffff6bcfcc0 <compositor>, extents=0x7fffffffbc60, boxes=0x7fffffffb9d0)
    at cairo-traps-compositor.c:1742
#18 0x00007ffff6b2f3dc in _cairo_traps_compositor_paint (_compositor=0x7ffff6bcfcc0 <compositor>, extents=0x7fffffffbc60) at cairo-traps-compositor.c:2063
#19 0x00007ffff6ad5301 in _cairo_compositor_paint (compositor=0x7ffff6bcfcc0 <compositor>, surface=0x555555cb5cb0, op=<optimized out>, source=<optimized out>, 
    clip=<optimized out>) at cairo-compositor.c:65
#20 0x00007ffff6b26f34 in _cairo_surface_paint (clip=0x555555cebbf0, source=0x7fffffffbf90, op=CAIRO_OPERATOR_OVER, surface=0x555555cb5cb0) at cairo-surface.c:2198
#21 _cairo_surface_paint (surface=0x555555cb5cb0, op=op@entry=CAIRO_OPERATOR_OVER, source=0x7fffffffbf90, clip=0x555555cebbf0) at cairo-surface.c:2171
#22 0x00007ffff6add31a in _cairo_gstate_paint (gstate=0x555555cd9e40) at cairo-gstate.c:1061
#23 0x00007ffff6b33e89 in INT_cairo_paint (cr=0x555555c95280) at cairo.c:2220
--Type <RET> for more, q to quit, c to continue without paging--
#24 0x00005555555950ea in display_draw (widget=<optimized out>, cr=0x555555c95280, data=<optimized out>) at eom-scroll-view.c:1376
#25 0x00007ffff7bcc7c8 in _gtk_marshal_BOOLEAN__BOXEDv (closure=closure@entry=0x555555c35e30, return_value=return_value@entry=0x7fffffffc470, 
    instance=instance@entry=0x555555c000f0, args=args@entry=0x7fffffffc540, marshal_data=marshal_data@entry=0x0, n_params=n_params@entry=1, param_types=0x55555563db40)
    at gtkmarshalers.c:129
#26 0x00007ffff7b7706c in gtk_widget_draw_marshallerv (closure=0x555555c35e30, return_value=0x7fffffffc470, instance=0x555555c000f0, args=0x7fffffffc540, 
    marshal_data=0x0, n_params=1, param_types=0x55555563db40) at gtkwidget.c:973
#27 0x00007ffff66fa636 in _g_closure_invoke_va (closure=0x555555c35e30, return_value=0x7fffffffc470, instance=0x555555c000f0, args=0x7fffffffc540, n_params=1, 
    param_types=0x55555563db40) at gclosure.c:873
#28 0x00007ffff6716524 in g_signal_emit_valist (instance=0x555555c000f0, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7fffffffc540) at gsignal.c:3300
#29 0x00007ffff67170a3 in g_signal_emit (instance=instance@entry=0x555555c000f0, signal_id=<optimized out>, detail=detail@entry=0) at gsignal.c:3447
#30 0x00007ffff7b83ef2 in gtk_widget_draw_internal (clip_to_size=1, cr=0x555555c95280, widget=0x555555c000f0) at gtkwidget.c:7025
#31 gtk_widget_draw_internal (widget=widget@entry=0x555555c000f0, cr=cr@entry=0x555555c95280, clip_to_size=clip_to_size@entry=1) at gtkwidget.c:6970
#32 0x00007ffff7966f50 in gtk_container_propagate_draw (container=container@entry=0x555555c42350, child=0x555555c000f0, cr=cr@entry=0x555555c95280)
    at gtkcontainer.c:3850
#33 0x00007ffff796701d in gtk_container_draw (widget=0x555555c42350, cr=cr@entry=0x555555c95280) at gtkcontainer.c:3670
#34 0x00007ffff79f2d48 in gtk_grid_render (gadget=<optimized out>, cr=0x555555c95280, x=<optimized out>, y=<optimized out>, width=<optimized out>, 
    height=<optimized out>, data=0x0) at gtkgrid.c:1713
#35 0x00007ffff796c231 in gtk_css_custom_gadget_draw (gadget=<optimized out>, cr=<optimized out>, x=<optimized out>, y=<optimized out>, width=<optimized out>, 
    height=<optimized out>) at gtkcsscustomgadget.c:159
#36 0x00007ffff797110a in gtk_css_gadget_draw (gadget=0x555555c37470, cr=0x555555c95280) at gtkcssgadget.c:885
#37 0x00007ffff79f3c85 in gtk_grid_draw (widget=<optimized out>, cr=<optimized out>) at gtkgrid.c:1722
#38 0x00007ffff7b83d94 in gtk_widget_draw_internal (clip_to_size=1, cr=0x555555c95280, widget=0x555555c42350) at gtkwidget.c:7032
#39 gtk_widget_draw_internal (widget=widget@entry=0x555555c42350, cr=cr@entry=0x555555c95280, clip_to_size=clip_to_size@entry=1) at gtkwidget.c:6970
#40 0x00007ffff7966f50 in gtk_container_propagate_draw (container=container@entry=0x555555b7e800, child=0x555555c42350, cr=cr@entry=0x555555c95280)
    at gtkcontainer.c:3850
#41 0x00007ffff7a68ed0 in gtk_paned_render (gadget=<optimized out>, cr=0x555555c95280, x=<optimized out>, y=<optimized out>, width=<optimized out>, 
    height=<optimized out>, data=0x0) at gtkpaned.c:1832
#42 0x00007ffff796c231 in gtk_css_custom_gadget_draw (gadget=<optimized out>, cr=<optimized out>, x=<optimized out>, y=<optimized out>, width=<optimized out>, 
    height=<optimized out>) at gtkcsscustomgadget.c:159
#43 0x00007ffff797110a in gtk_css_gadget_draw (gadget=0x555555c2c400, cr=0x555555c95280) at gtkcssgadget.c:885
#44 0x00007ffff7a68ce5 in gtk_paned_draw (widget=<optimized out>, cr=<optimized out>) at gtkpaned.c:1782
#45 0x00007ffff7b83d94 in gtk_widget_draw_internal (clip_to_size=1, cr=0x555555c95280, widget=0x555555b7e800) at gtkwidget.c:7032
#46 gtk_widget_draw_internal (widget=widget@entry=0x555555b7e800, cr=cr@entry=0x555555c95280, clip_to_size=clip_to_size@entry=1) at gtkwidget.c:6970
#47 0x00007ffff7966f50 in gtk_container_propagate_draw (container=container@entry=0x555555c361b0, child=0x555555b7e800, cr=cr@entry=0x555555c95280)
    at gtkcontainer.c:3850
#48 0x00007ffff796701d in gtk_container_draw (widget=0x555555c361b0, cr=cr@entry=0x555555c95280) at gtkcontainer.c:3670
#49 0x00007ffff7917f08 in gtk_box_draw_contents (gadget=<optimized out>, cr=0x555555c95280, x=<optimized out>, y=<optimized out>, width=<optimized out>, 
--Type <RET> for more, q to quit, c to continue without paging--
    height=<optimized out>, unused=0x0) at gtkbox.c:448
#50 0x00007ffff796c231 in gtk_css_custom_gadget_draw (gadget=<optimized out>, cr=<optimized out>, x=<optimized out>, y=<optimized out>, width=<optimized out>, 
    height=<optimized out>) at gtkcsscustomgadget.c:159
#51 0x00007ffff797110a in gtk_css_gadget_draw (gadget=0x555555c2c080, cr=0x555555c95280) at gtkcssgadget.c:885
#52 0x00007ffff791a8b5 in gtk_box_draw (widget=<optimized out>, cr=<optimized out>) at gtkbox.c:457
#53 0x00007ffff7b83d94 in gtk_widget_draw_internal (clip_to_size=1, cr=0x555555c95280, widget=0x555555c361b0) at gtkwidget.c:7032
#54 gtk_widget_draw_internal (widget=widget@entry=0x555555c361b0, cr=cr@entry=0x555555c95280, clip_to_size=clip_to_size@entry=1) at gtkwidget.c:6970
#55 0x00007ffff7966f50 in gtk_container_propagate_draw (container=container@entry=0x555555b4cc80, child=0x555555c361b0, cr=cr@entry=0x555555c95280)
    at gtkcontainer.c:3850
#56 0x00007ffff796701d in gtk_container_draw (widget=0x555555b4cc80, cr=cr@entry=0x555555c95280) at gtkcontainer.c:3670
#57 0x00007ffff7917f08 in gtk_box_draw_contents (gadget=<optimized out>, cr=0x555555c95280, x=<optimized out>, y=<optimized out>, width=<optimized out>, 
    height=<optimized out>, unused=0x0) at gtkbox.c:448
#58 0x00007ffff796c231 in gtk_css_custom_gadget_draw (gadget=<optimized out>, cr=<optimized out>, x=<optimized out>, y=<optimized out>, width=<optimized out>, 
    height=<optimized out>) at gtkcsscustomgadget.c:159
#59 0x00007ffff797110a in gtk_css_gadget_draw (gadget=0x555555b85890, cr=0x555555c95280) at gtkcssgadget.c:885
#60 0x00007ffff791a8b5 in gtk_box_draw (widget=<optimized out>, cr=<optimized out>) at gtkbox.c:457
#61 0x00007ffff7b83d94 in gtk_widget_draw_internal (clip_to_size=1, cr=0x555555c95280, widget=0x555555b4cc80) at gtkwidget.c:7032
#62 gtk_widget_draw_internal (widget=widget@entry=0x555555b4cc80, cr=cr@entry=0x555555c95280, clip_to_size=clip_to_size@entry=1) at gtkwidget.c:6970
#63 0x00007ffff7966f50 in gtk_container_propagate_draw (container=container@entry=0x555555976180, child=0x555555b4cc80, cr=cr@entry=0x555555c95280)
    at gtkcontainer.c:3850
#64 0x00007ffff796701d in gtk_container_draw (widget=0x555555976180, cr=cr@entry=0x555555c95280) at gtkcontainer.c:3670
#65 0x00007ffff7917f08 in gtk_box_draw_contents (gadget=<optimized out>, cr=0x555555c95280, x=<optimized out>, y=<optimized out>, width=<optimized out>, 
    height=<optimized out>, unused=0x0) at gtkbox.c:448
#66 0x00007ffff796c231 in gtk_css_custom_gadget_draw (gadget=<optimized out>, cr=<optimized out>, x=<optimized out>, y=<optimized out>, width=<optimized out>, 
    height=<optimized out>) at gtkcsscustomgadget.c:159
#67 0x00007ffff797110a in gtk_css_gadget_draw (gadget=0x555555768a00, cr=0x555555c95280) at gtkcssgadget.c:885
#68 0x00007ffff791a8b5 in gtk_box_draw (widget=<optimized out>, cr=<optimized out>) at gtkbox.c:457
#69 0x00007ffff7b83d94 in gtk_widget_draw_internal (clip_to_size=1, cr=0x555555c95280, widget=0x555555976180) at gtkwidget.c:7032
#70 gtk_widget_draw_internal (widget=widget@entry=0x555555976180, cr=cr@entry=0x555555c95280, clip_to_size=clip_to_size@entry=1) at gtkwidget.c:6970
#71 0x00007ffff7966f50 in gtk_container_propagate_draw (container=container@entry=0x55555562a330, child=0x555555976180, cr=cr@entry=0x555555c95280)
    at gtkcontainer.c:3850
#72 0x00007ffff796701d in gtk_container_draw (widget=0x55555562a330, cr=0x555555c95280) at gtkcontainer.c:3670
#73 0x00007ffff7b924a6 in gtk_window_draw (widget=0x55555562a330, cr=0x555555c95280) at gtkwindow.c:10420
#74 0x00007ffff7b83d94 in gtk_widget_draw_internal (clip_to_size=<optimized out>, cr=0x555555c95280, widget=0x55555562a330) at gtkwidget.c:7032
#75 gtk_widget_draw_internal (widget=0x55555562a330, cr=0x555555c95280, clip_to_size=<optimized out>) at gtkwidget.c:6970
#76 0x00007ffff7b8d030 in gtk_widget_render (widget=widget@entry=0x55555562a330, window=0x5555556244b0, region=<optimized out>) at gtkwidget.c:17542
#77 0x00007ffff7a37999 in gtk_main_do_event (event=0x7fffffffd390) at gtkmain.c:1838
--Type <RET> for more, q to quit, c to continue without paging--
#78 gtk_main_do_event (event=<optimized out>) at gtkmain.c:1685
#79 0x00007ffff7728a39 in _gdk_event_emit (event=event@entry=0x7fffffffd390) at gdkevents.c:73
#80 0x00007ffff7739766 in _gdk_window_process_updates_recurse_helper (window=0x5555556244b0, expose_region=<optimized out>) at gdkwindow.c:3852
#81 0x00007ffff773a936 in gdk_window_process_updates_internal (window=0x5555556244b0) at gdkwindow.c:3998
#82 0x00007ffff773aaf4 in gdk_window_process_updates_with_mode (recurse_mode=<optimized out>, window=<optimized out>) at gdkwindow.c:4193
#83 gdk_window_process_updates_with_mode (window=<optimized out>, recurse_mode=<optimized out>) at gdkwindow.c:4164
#84 0x00007ffff66fa3dd in g_closure_invoke (closure=0x555555c8cc00, return_value=0x0, n_param_values=1, param_values=0x7fffffffd660, invocation_hint=0x7fffffffd5e0)
    at gclosure.c:810
#85 0x00007ffff670d983 in signal_emit_unlocked_R (node=node@entry=0x555555635700, detail=detail@entry=0, instance=instance@entry=0x555555636290, 
    emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffffffd660) at gsignal.c:3635
#86 0x00007ffff6716aaa in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffd820)
    at gsignal.c:3391
#87 0x00007ffff67170a3 in g_signal_emit (instance=instance@entry=0x555555636290, signal_id=<optimized out>, detail=detail@entry=0) at gsignal.c:3447
#88 0x00007ffff7731d93 in _gdk_frame_clock_emit_paint (frame_clock=frame_clock@entry=0x555555636290) at gdkframeclock.c:640
#89 0x00007ffff773253d in gdk_frame_clock_paint_idle (data=0x555555636290) at gdkframeclockidle.c:459
#90 0x00007ffff771cbac in gdk_threads_dispatch (data=data@entry=0x5555557ef3a0) at gdk.c:755
#91 0x00007ffff6618b31 in g_timeout_dispatch (source=0x555555cbd8b0, callback=0x7ffff771cb80 <gdk_threads_dispatch>, user_data=0x5555557ef3a0) at gmain.c:4667
#92 0x00007ffff661806d in g_main_dispatch (context=0x555555633940) at gmain.c:3182
#93 g_main_context_dispatch (context=context@entry=0x555555633940) at gmain.c:3847
#94 0x00007ffff6618438 in g_main_context_iterate (context=0x555555633940, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3920
#95 0x00007ffff6618762 in g_main_loop_run (loop=0x555555c0de80) at gmain.c:4116
#96 0x00007ffff7a36b6d in gtk_main () at gtkmain.c:1323
#97 0x0000555555578a0c in main (argc=<optimized out>, argv=<optimized out>) at main.c:268
```

**Comment by baryluk** [comment]
Here is a 200Megapixel single frame as a JPG at a lukewarm 64MB file size:

http://bit.ly/2GjQWBZ

EOM fails to display it.

GIMP, Firefox, Geeqie, feh, Mirage, Ephoto, pqiv, GLiv, nomacs, Gwenview, Shotwell show it perfectly fine, and load it very quickly, with zoom and panning also all smooth.

ristretto Image Viewer, does also fail to properly display it, but it does show the correct thumbnail. After opening the image in ristretto, opening any other files also fails - a program need to be restarted.

**Comment by raveit65** [comment]
Our document-viewer atril can open this file.
